# Deploy Aztec Bridge to Vercel following the recommended pattern
name: Deploy Aztec Bridge to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_AZTEC_BRIDGE_PROJECT_ID }}
  FAUCET_PRIVATE_KEY: ${{ secrets.FAUCET_PRIVATE_KEY }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/setup-pnpm-and-install
        with:
          pnpm-version: 8
          working-directory: ./frontend

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Build Next App
        working-directory: ./frontend
        run: pnpm build
            
      - name: Pull Preview Environment From Vercel
        working-directory: ./frontend
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  
  Deploy-Production:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref_name == 'main'
    needs: Deploy-Preview
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-pnpm-and-install
        with:
          pnpm-version: 8
          working-directory: ./frontend

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Build Next App
        working-directory: ./frontend
        run: pnpm build
      
      - name: Pull Production Environment From Vercel
        working-directory: ./frontend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        working-directory: frontend
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} 
        
      - name: Deploy to Production
        working-directory: ./frontend
        run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      